In [1]:
import numpy as np
import cv2

In [2]:
image = cv2.imread("Y:\\Dataset\\CASIA Iris Image Database (version 1.0)\\003\\1\\003_1_2.bmp",0)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
image.shape

(280, 320)

In [17]:
otsu_threshold, images_result = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
print("Obtained threshold: ", otsu_threshold)

Obtained threshold:  161.0


In [12]:
image

array([[215, 217, 214, ..., 203, 196, 194],
       [226, 214, 217, ..., 196, 193, 188],
       [219, 210, 218, ..., 201, 197, 193],
       ...,
       [168, 175, 170, ..., 230, 211, 203],
       [171, 166, 156, ..., 225, 216, 205],
       [171, 168, 154, ..., 209, 214, 210]], dtype=uint8)

In [5]:
original_image = image.ravel()
otsu_image = images_result.ravel()

In [13]:
print(original_image)
print(otsu_image)

[215 217 214 ... 209 214 210]
[255 255 255 ... 255 255 255]


In [24]:
lower_half = []
upper_half = []
thresh = otsu_threshold

for x in original_image:
    if(x >= thresh):
        upper_half.append(x)
    else:
        lower_half.append(x)
        

print(lower_half)
print(upper_half)



161.0
[157, 148, 149, 142, 138, 135, 129, 154, 123, 158, 125, 148, 157, 120, 155, 124, 157, 155, 125, 156, 125, 153, 151, 158, 137, 153, 153, 150, 128, 153, 153, 154, 155, 142, 153, 158, 154, 144, 136, 149, 160, 135, 159, 141, 140, 145, 150, 140, 133, 146, 147, 160, 151, 143, 146, 115, 124, 151, 146, 146, 143, 139, 160, 160, 152, 135, 142, 130, 137, 107, 120, 143, 149, 153, 144, 107, 113, 142, 160, 146, 151, 147, 128, 126, 142, 128, 135, 122, 100, 118, 142, 149, 138, 115, 119, 140, 160, 157, 159, 156, 150, 116, 123, 149, 147, 130, 140, 134, 155, 153, 149, 146, 139, 127, 155, 158, 159, 159, 150, 148, 153, 158, 158, 150, 153, 148, 150, 142, 142, 154, 149, 144, 158, 159, 153, 140, 160, 158, 142, 156, 149, 144, 150, 150, 110, 132, 158, 158, 154, 160, 159, 150, 147, 144, 142, 155, 134, 145, 141, 134, 156, 149, 144, 150, 122, 109, 149, 156, 140, 137, 139, 137, 154, 157, 153, 159, 138, 126, 140, 132, 128, 120, 130, 128, 140, 155, 146, 125, 153, 135, 110, 141, 150, 156, 158, 129, 137, 138, 106

In [26]:
otsu_upper_avg = np.mean(upper_half)
otsu_lower_avg = np.mean(lower_half)

print(otsu_upper_avg)
print(otsu_lower_avg)

198.80489999590986
122.53921183234239


In [11]:
cv2.imshow('image',image)
cv2.imshow('image_result',images_result)
cv2.waitKey(0)
cv2.destroyAllWindows()